use bzip2::read::BzDecoder;
use regex::bytes::Regex;
use reqwest::Client;
use serde::{Deserialize, Serialize};
use std::fs::{self, File};
use std::io::{self, BufReader, BufWriter, Read, Write};
use std::path::{Path, PathBuf};
use std::time::Duration;
use tar::Archive;
use walkdir::WalkDir;

const RELEASES_API: &str = "https://api.github.com/repos/Detanup01/gbe_fork/releases/latest";
const USER_AGENT: &str = "SteamManifestDownloader";

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum Variant {
    Regular,
    Experimental,
}

impl Variant {
    fn folder(self) -> &'static str {
        match self {
            Variant::Regular => "regular",
            Variant::Experimental => "experimental",
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum Platform {
    Windows,
    Linux,
}

impl Platform {
    fn asset_name(self) -> &'static str {
        match self {
            Platform::Windows => "emu-win-release-vs22.7z",
            Platform::Linux => "emu-linux-release.tar.bz2",
        }
    }
    pub fn cache_subdir(self) -> &'static str {
        match self {
            Platform::Windows => "windows",
            Platform::Linux => "linux",
        }
    }
    fn emu_filename(self, x64: bool) -> &'static str {
        match (self, x64) {
            (Platform::Windows, true) => "steam_api64.dll",
            (Platform::Windows, false) => "steam_api.dll",
            (Platform::Linux, _) => "libsteam_api.so",
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ReleaseInfo {
    pub tag: String,
    pub published_at: String,
    pub windows_url: String,
    pub windows_size: u64,
    pub linux_url: String,
    pub linux_size: u64,
    pub windows_cached: bool,
    pub linux_cached: bool,
    pub cache_root: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ScannedFile {
    pub path: String,
    pub platform: Platform,
    pub arch: String,
    pub is_patched: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ReplaceResult {
    pub path: String,
    pub backup_path: Option<String>,
    pub success: bool,
    pub error: Option<String>,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default)]
pub struct EmuSettings {
    pub account_name: Option<String>,
    pub account_steamid: Option<String>,
    pub language: Option<String>,
    pub ip_country: Option<String>,
    pub local_save_path: Option<String>,
    pub saves_folder_name: Option<String>,
    pub offline: Option<bool>,
    pub steam_deck: Option<bool>,
    pub disable_networking: Option<bool>,
    pub disable_lan_only: Option<bool>,
    pub record_playtime: Option<bool>,
    pub achievements_bypass: Option<bool>,
    pub force_steamhttp_success: Option<bool>,
    pub enable_steam_preowned_ids: Option<bool>,
    pub free_weekend: Option<bool>,
    pub enable_experimental_overlay: Option<bool>,
    pub disable_achievement_notification: Option<bool>,
    pub overlay_always_show_fps: Option<bool>,
    pub overlay_always_show_playtime: Option<bool>,
    pub key_combo: Option<String>,
    pub font_size: Option<f32>,
}

const INI_HEADER: &str = "# Generated by Steam Manifest Downloader.\n# Edit these settings via the in-app emulator step. Any keys not managed\n# here will be overwritten on re-apply.\n\n";

fn bool_to_ini(b: bool) -> &'static str {
    if b { "1" } else { "0" }
}

fn ini_from_bool(s: &str) -> Option<bool> {
    match s.trim() {
        "1" | "true" | "yes" | "on" => Some(true),
        "0" | "false" | "no" | "off" => Some(false),
        _ => None,
    }
}

fn parse_ini_sections(text: &str) -> std::collections::HashMap<String, std::collections::HashMap<String, String>> {
    let mut out: std::collections::HashMap<String, std::collections::HashMap<String, String>> =
        std::collections::HashMap::new();
    let mut current: Option<String> = None;
    for raw in text.lines() {
        let line = raw.trim();
        if line.is_empty() || line.starts_with('#') || line.starts_with(';') {
            continue;
        }
        if line.starts_with('[') && line.ends_with(']') {
            current = Some(line[1..line.len() - 1].trim().to_string());
            continue;
        }
        let Some(section) = current.as_ref() else { continue };
        let Some(eq) = line.find('=') else { continue };
        let key = line[..eq].trim().to_string();
        let val = line[eq + 1..].trim().to_string();
        out.entry(section.clone()).or_default().insert(key, val);
    }
    out
}

impl EmuSettings {
    pub fn render_user_ini(&self) -> String {
        let mut sections: Vec<(String, Vec<(String, String)>)> = Vec::new();

        let mut general = Vec::new();
        if let Some(v) = &self.account_name { general.push(("account_name".into(), v.clone())); }
        if let Some(v) = &self.account_steamid { general.push(("account_steamid".into(), v.clone())); }
        if let Some(v) = &self.language { general.push(("language".into(), v.clone())); }
        if let Some(v) = &self.ip_country { general.push(("ip_country".into(), v.clone())); }
        if !general.is_empty() { sections.push(("user::general".into(), general)); }

        let mut saves = Vec::new();
        if let Some(v) = &self.local_save_path { saves.push(("local_save_path".into(), v.clone())); }
        if let Some(v) = &self.saves_folder_name { saves.push(("saves_folder_name".into(), v.clone())); }
        if !saves.is_empty() { sections.push(("user::saves".into(), saves)); }

        render_sections(&sections)
    }

    pub fn render_main_ini(&self) -> String {
        let mut sections: Vec<(String, Vec<(String, String)>)> = Vec::new();

        let mut general = Vec::new();
        if let Some(v) = self.offline { general.push(("offline".into(), bool_to_ini(v).into())); }
        if let Some(v) = self.steam_deck { general.push(("steam_deck".into(), bool_to_ini(v).into())); }
        if !general.is_empty() { sections.push(("main::general".into(), general)); }

        let mut conn = Vec::new();
        if let Some(v) = self.disable_networking { conn.push(("disable_networking".into(), bool_to_ini(v).into())); }
        if let Some(v) = self.disable_lan_only { conn.push(("disable_lan_only".into(), bool_to_ini(v).into())); }
        if !conn.is_empty() { sections.push(("main::connectivity".into(), conn)); }

        let mut stats = Vec::new();
        if let Some(v) = self.record_playtime { stats.push(("record_playtime".into(), bool_to_ini(v).into())); }
        if !stats.is_empty() { sections.push(("main::stats".into(), stats)); }

        let mut misc = Vec::new();
        if let Some(v) = self.achievements_bypass { misc.push(("achievements_bypass".into(), bool_to_ini(v).into())); }
        if let Some(v) = self.force_steamhttp_success { misc.push(("force_steamhttp_success".into(), bool_to_ini(v).into())); }
        if let Some(v) = self.enable_steam_preowned_ids { misc.push(("enable_steam_preowned_ids".into(), bool_to_ini(v).into())); }
        if let Some(v) = self.free_weekend { misc.push(("free_weekend".into(), bool_to_ini(v).into())); }
        if !misc.is_empty() { sections.push(("main::misc".into(), misc)); }

        render_sections(&sections)
    }

    pub fn render_overlay_ini(&self) -> String {
        let mut sections: Vec<(String, Vec<(String, String)>)> = Vec::new();

        let mut general = Vec::new();
        if let Some(v) = self.enable_experimental_overlay { general.push(("enable_experimental_overlay".into(), bool_to_ini(v).into())); }
        if let Some(v) = self.disable_achievement_notification { general.push(("disable_achievement_notification".into(), bool_to_ini(v).into())); }
        if let Some(v) = self.overlay_always_show_fps { general.push(("overlay_always_show_fps".into(), bool_to_ini(v).into())); }
        if let Some(v) = self.overlay_always_show_playtime { general.push(("overlay_always_show_playtime".into(), bool_to_ini(v).into())); }
        if !general.is_empty() { sections.push(("overlay::general".into(), general)); }

        let mut hotkeys = Vec::new();
        if let Some(v) = &self.key_combo { hotkeys.push(("key_combo".into(), v.clone())); }
        if !hotkeys.is_empty() { sections.push(("overlay::hotkeys".into(), hotkeys)); }

        let mut appearance = Vec::new();
        if let Some(v) = self.font_size { appearance.push(("Font_Size".into(), format!("{}", v))); }
        if !appearance.is_empty() { sections.push(("overlay::appearance".into(), appearance)); }

        render_sections(&sections)
    }

    pub fn write_to_dir(&self, dir: &Path) -> Result<(), String> {
        fs::create_dir_all(dir).map_err(|e| format!("create steam_settings: {}", e))?;
        let write_or_remove = |name: &str, content: String| -> Result<(), String> {
            let path = dir.join(name);
            if content.trim().is_empty() {
                let _ = fs::remove_file(&path);
                return Ok(());
            }
            fs::write(&path, content).map_err(|e| format!("write {}: {}", name, e))
        };
        write_or_remove("configs.user.ini", self.render_user_ini())?;
        write_or_remove("configs.main.ini", self.render_main_ini())?;
        write_or_remove("configs.overlay.ini", self.render_overlay_ini())?;
        Ok(())
    }

    pub fn read_from_dir(dir: &Path) -> EmuSettings {
        let mut s = EmuSettings::default();
        if let Ok(text) = fs::read_to_string(dir.join("configs.user.ini")) {
            s.absorb_user(&text);
        }
        if let Ok(text) = fs::read_to_string(dir.join("configs.main.ini")) {
            s.absorb_main(&text);
        }
        if let Ok(text) = fs::read_to_string(dir.join("configs.overlay.ini")) {
            s.absorb_overlay(&text);
        }
        s
    }

    fn absorb_user(&mut self, text: &str) {
        let parsed = parse_ini_sections(text);
        if let Some(sec) = parsed.get("user::general") {
            if let Some(v) = sec.get("account_name") { self.account_name = Some(v.clone()); }
            if let Some(v) = sec.get("account_steamid") { self.account_steamid = Some(v.clone()); }
            if let Some(v) = sec.get("language") { self.language = Some(v.clone()); }
            if let Some(v) = sec.get("ip_country") { self.ip_country = Some(v.clone()); }
        }
        if let Some(sec) = parsed.get("user::saves") {
            if let Some(v) = sec.get("local_save_path") { self.local_save_path = Some(v.clone()); }
            if let Some(v) = sec.get("saves_folder_name") { self.saves_folder_name = Some(v.clone()); }
        }
    }

    fn absorb_main(&mut self, text: &str) {
        let parsed = parse_ini_sections(text);
        if let Some(sec) = parsed.get("main::general") {
            if let Some(v) = sec.get("offline") { self.offline = ini_from_bool(v); }
            if let Some(v) = sec.get("steam_deck") { self.steam_deck = ini_from_bool(v); }
        }
        if let Some(sec) = parsed.get("main::connectivity") {
            if let Some(v) = sec.get("disable_networking") { self.disable_networking = ini_from_bool(v); }
            if let Some(v) = sec.get("disable_lan_only") { self.disable_lan_only = ini_from_bool(v); }
        }
        if let Some(sec) = parsed.get("main::stats") {
            if let Some(v) = sec.get("record_playtime") { self.record_playtime = ini_from_bool(v); }
        }
        if let Some(sec) = parsed.get("main::misc") {
            if let Some(v) = sec.get("achievements_bypass") { self.achievements_bypass = ini_from_bool(v); }
            if let Some(v) = sec.get("force_steamhttp_success") { self.force_steamhttp_success = ini_from_bool(v); }
            if let Some(v) = sec.get("enable_steam_preowned_ids") { self.enable_steam_preowned_ids = ini_from_bool(v); }
            if let Some(v) = sec.get("free_weekend") { self.free_weekend = ini_from_bool(v); }
        }
    }

    fn absorb_overlay(&mut self, text: &str) {
        let parsed = parse_ini_sections(text);
        if let Some(sec) = parsed.get("overlay::general") {
            if let Some(v) = sec.get("enable_experimental_overlay") { self.enable_experimental_overlay = ini_from_bool(v); }
            if let Some(v) = sec.get("disable_achievement_notification") { self.disable_achievement_notification = ini_from_bool(v); }
            if let Some(v) = sec.get("overlay_always_show_fps") { self.overlay_always_show_fps = ini_from_bool(v); }
            if let Some(v) = sec.get("overlay_always_show_playtime") { self.overlay_always_show_playtime = ini_from_bool(v); }
        }
        if let Some(sec) = parsed.get("overlay::hotkeys") {
            if let Some(v) = sec.get("key_combo") { self.key_combo = Some(v.clone()); }
        }
        if let Some(sec) = parsed.get("overlay::appearance") {
            if let Some(v) = sec.get("Font_Size") {
                if let Ok(n) = v.parse::<f32>() { self.font_size = Some(n); }
            }
        }
    }
}

fn render_sections(sections: &[(String, Vec<(String, String)>)]) -> String {
    if sections.is_empty() {
        return String::new();
    }
    let mut out = String::from(INI_HEADER);
    for (i, (name, kvs)) in sections.iter().enumerate() {
        if i > 0 {
            out.push('\n');
        }
        out.push('[');
        out.push_str(name);
        out.push_str("]\n");
        for (k, v) in kvs {
            out.push_str(k);
            out.push('=');
            out.push_str(v);
            out.push('\n');
        }
    }
    out
}

fn cache_root(app_data_dir: &Path) -> PathBuf {
    app_data_dir.join("gbe_fork_cache")
}

pub async fn fetch_release_info(client: &Client, app_data_dir: &Path) -> Result<ReleaseInfo, String> {
    let resp = client
        .get(RELEASES_API)
        .header("User-Agent", USER_AGENT)
        .header("Accept", "application/vnd.github+json")
        .timeout(Duration::from_secs(30))
        .send()
        .await
        .map_err(|e| format!("GitHub fetch failed: {}", e))?;

    if !resp.status().is_success() {
        return Err(format!("GitHub returned HTTP {}", resp.status()));
    }

    let body: serde_json::Value = resp
        .json()
        .await
        .map_err(|e| format!("GitHub JSON parse failed: {}", e))?;

    let tag = body
        .get("tag_name")
        .and_then(|v| v.as_str())
        .ok_or("Missing tag_name in release info")?
        .to_string();
    let published_at = body
        .get("published_at")
        .and_then(|v| v.as_str())
        .unwrap_or("")
        .to_string();

    let assets = body
        .get("assets")
        .and_then(|v| v.as_array())
        .ok_or("Missing assets array")?;

    let pick = |name: &str| -> Result<(String, u64), String> {
        let a = assets
            .iter()
            .find(|a| a.get("name").and_then(|v| v.as_str()) == Some(name))
            .ok_or_else(|| format!("Asset {} not present in release", name))?;
        let url = a
            .get("browser_download_url")
            .and_then(|v| v.as_str())
            .ok_or("Asset has no browser_download_url")?
            .to_string();
        let size = a.get("size").and_then(|v| v.as_u64()).unwrap_or(0);
        Ok((url, size))
    };

    let (windows_url, windows_size) = pick(Platform::Windows.asset_name())?;
    let (linux_url, linux_size) = pick(Platform::Linux.asset_name())?;

    let root = cache_root(app_data_dir).join(&tag);
    let windows_cached = root.join(Platform::Windows.cache_subdir()).join(".extracted").exists();
    let linux_cached = root.join(Platform::Linux.cache_subdir()).join(".extracted").exists();

    Ok(ReleaseInfo {
        tag,
        published_at,
        windows_url,
        windows_size,
        linux_url,
        linux_size,
        windows_cached,
        linux_cached,
        cache_root: root.to_string_lossy().to_string(),
    })
}

pub async fn ensure_cached(
    client: &Client,
    info: &ReleaseInfo,
    platform: Platform,
) -> Result<PathBuf, String> {
    let platform_dir = PathBuf::from(&info.cache_root).join(platform.cache_subdir());
    let extracted_marker = platform_dir.join(".extracted");
    if extracted_marker.exists() {
        return Ok(platform_dir);
    }

    fs::create_dir_all(&platform_dir).map_err(|e| format!("create cache dir: {}", e))?;
    let asset_name = platform.asset_name();
    let asset_url = match platform {
        Platform::Windows => &info.windows_url,
        Platform::Linux => &info.linux_url,
    };
    let archive_path = platform_dir.join(asset_name);

    if !archive_path.exists() {
        let mut resp = client
            .get(asset_url)
            .header("User-Agent", USER_AGENT)
            .timeout(Duration::from_secs(600))
            .send()
            .await
            .map_err(|e| format!("download failed: {}", e))?;
        if !resp.status().is_success() {
            return Err(format!("download returned HTTP {}", resp.status()));
        }
        let tmp_path = platform_dir.join(format!("{}.part", asset_name));
        {
            let mut file =
                BufWriter::new(File::create(&tmp_path).map_err(|e| format!("create archive: {}", e))?);
            while let Some(chunk) = resp.chunk().await.map_err(|e| format!("chunk: {}", e))? {
                file.write_all(&chunk).map_err(|e| format!("write archive: {}", e))?;
            }
            file.flush().map_err(|e| format!("flush archive: {}", e))?;
        }
        fs::rename(&tmp_path, &archive_path).map_err(|e| format!("finalize archive: {}", e))?;
    }

    if let Err(e) = extract_archive(&archive_path, &platform_dir, platform) {
        if e.starts_with("AV_BLOCKED") {
            let _ = fs::remove_file(&archive_path);
        }
        return Err(e);
    }
    fs::write(&extracted_marker, info.tag.as_bytes())
        .map_err(|e| format!("write extracted marker: {}", e))?;

    Ok(platform_dir)
}

fn extract_archive(archive: &Path, dst: &Path, platform: Platform) -> Result<(), String> {
    match platform {
        Platform::Linux => extract_tar_bz2(archive, dst),
        Platform::Windows => extract_7z(archive, dst),
    }
}

fn extract_tar_bz2(archive: &Path, dst: &Path) -> Result<(), String> {
    let file = File::open(archive).map_err(|e| format!("open archive: {}", e))?;
    let mut decoder = BzDecoder::new(BufReader::new(file));
    let mut tmp = Vec::with_capacity(64 * 1024 * 1024);
    decoder
        .read_to_end(&mut tmp)
        .map_err(|e| format!("bzip2 decompress: {}", e))?;
    let mut tar = Archive::new(io::Cursor::new(tmp));
    tar.unpack(dst).map_err(|e| format!("tar unpack: {}", e))?;
    Ok(())
}

fn extract_7z(archive: &Path, dst: &Path) -> Result<(), String> {
    sevenz_rust::decompress_file(archive, dst).map_err(|e| {
        let msg = e.to_string();
        if is_antivirus_block(&msg) {
            format!("AV_BLOCKED: {}", msg)
        } else {
            format!("7z decompress: {}", msg)
        }
    })
}

fn is_antivirus_block(msg: &str) -> bool {
    let lower = msg.to_lowercase();
    msg.contains("code: 225")
        || lower.contains("virus")
        || lower.contains("unerwünschte software")
        || lower.contains("unwanted software")
}

fn release_root(platform_cache: &Path) -> PathBuf {
    platform_cache.join("release")
}

pub fn dll_source(
    platform_cache: &Path,
    variant: Variant,
    x64: bool,
    platform: Platform,
) -> Result<PathBuf, String> {
    let root = release_root(platform_cache).join(variant.folder());
    let arch_dir = if x64 { "x64" } else { "x32" };
    let p = root.join(arch_dir).join(platform.emu_filename(x64));
    if p.exists() {
        Ok(p)
    } else {
        Err(format!("emulator binary not found at {}", p.display()))
    }
}

pub fn scan_game_dir(game_dir: &Path) -> Vec<ScannedFile> {
    let mut out = Vec::new();
    if !game_dir.exists() {
        return out;
    }
    for entry in WalkDir::new(game_dir).follow_links(false).into_iter().flatten() {
        if !entry.file_type().is_file() {
            continue;
        }
        let name = entry.file_name().to_string_lossy().to_ascii_lowercase();
        let (platform, arch) = if name == "steam_api64.dll" {
            (Platform::Windows, "x64")
        } else if name == "steam_api.dll" {
            (Platform::Windows, "x32")
        } else if name == "libsteam_api.so" {
            (Platform::Linux, detect_so_arch(entry.path()))
        } else {
            continue;
        };
        let is_patched = backup_path_for(entry.path()).exists();
        out.push(ScannedFile {
            path: entry.path().to_string_lossy().to_string(),
            platform,
            arch: arch.to_string(),
            is_patched,
        });
    }
    out
}

fn detect_so_arch(path: &Path) -> &'static str {
    let Ok(mut file) = File::open(path) else {
        return "x64";
    };
    let mut header = [0u8; 5];
    if file.read_exact(&mut header).is_err() {
        return "x64";
    }
    if &header[..4] != b"\x7fELF" {
        return "x64";
    }
    match header[4] {
        1 => "x32",
        2 => "x64",
        _ => "x64",
    }
}

const INTERFACE_PATTERNS: &[&str] = &[
    r"STEAMAPPS_INTERFACE_VERSION\d+",
    r"SteamApps\d+",
    r"STEAMAPPLIST_INTERFACE_VERSION\d+",
    r"STEAMAPPTICKET_INTERFACE_VERSION\d+",
    r"SteamClient\d+",
    r"STEAMCONTROLLER_INTERFACE_VERSION",
    r"SteamController\d+",
    r"SteamFriends\d+",
    r"SteamGameServerStats\d+",
    r"SteamGameCoordinator\d+",
    r"SteamGameServer\d+",
    r"STEAMHTMLSURFACE_INTERFACE_VERSION_\d+",
    r"STEAMHTTP_INTERFACE_VERSION\d+",
    r"SteamInput\d+",
    r"STEAMINVENTORY_INTERFACE_V\d+",
    r"SteamMatchMakingServers\d+",
    r"SteamMatchMaking\d+",
    r"SteamMatchGameSearch\d+",
    r"SteamParties\d+",
    r"STEAMMUSIC_INTERFACE_VERSION\d+",
    r"STEAMMUSICREMOTE_INTERFACE_VERSION\d+",
    r"SteamNetworkingMessages\d+",
    r"SteamNetworkingSockets\d+",
    r"SteamNetworkingUtils\d+",
    r"SteamNetworking\d+",
    r"STEAMPARENTALSETTINGS_INTERFACE_VERSION\d+",
    r"STEAMREMOTEPLAY_INTERFACE_VERSION\d+",
    r"STEAMREMOTESTORAGE_INTERFACE_VERSION\d+",
    r"STEAMSCREENSHOTS_INTERFACE_VERSION\d+",
    r"STEAMTIMELINE_INTERFACE_V\d+",
    r"STEAMUGC_INTERFACE_VERSION\d+",
    r"SteamUser\d+",
    r"STEAMUSERSTATS_INTERFACE_VERSION\d+",
    r"SteamUtils\d+",
    r"STEAMVIDEO_INTERFACE_V\d+",
    r"STEAMUNIFIEDMESSAGES_INTERFACE_VERSION\d+",
    r"SteamMasterServerUpdater\d+",
];

pub fn generate_interfaces(dll_bytes: &[u8]) -> Result<String, String> {
    let mut out = String::new();
    let mut total: usize = 0;
    for patt in INTERFACE_PATTERNS {
        let re = Regex::new(patt).map_err(|e| format!("bad pattern '{}': {}", patt, e))?;
        let mut matches: Vec<Vec<u8>> = re
            .find_iter(dll_bytes)
            .map(|m| m.as_bytes().to_vec())
            .collect();

        if *patt == r"SteamClient\d+" && matches.len() > 1 {
            let has_017 = matches.iter().any(|m| m == b"SteamClient017");
            if has_017 {
                matches.retain(|m| m == b"SteamClient017");
            }
        }

        for m in matches {
            if let Ok(s) = std::str::from_utf8(&m) {
                out.push_str(s);
                out.push('\n');
                total += 1;
            }
        }
    }
    if total == 0 {
        return Err("No Steam interfaces found in the binary".into());
    }
    Ok(out)
}

fn generate_interfaces_from_file(target: &Path) -> Result<String, String> {
    let bytes = fs::read(target).map_err(|e| format!("read {}: {}", target.display(), e))?;
    generate_interfaces(&bytes)
}

pub fn apply_replacement(
    target: &Path,
    platform_cache: &Path,
    variant: Variant,
    platform: Platform,
    x64: bool,
    app_id: &str,
    installed_app_ids: &[String],
    emu_settings: Option<&EmuSettings>,
) -> ReplaceResult {
    let mut result = ReplaceResult {
        path: target.to_string_lossy().to_string(),
        backup_path: None,
        success: false,
        error: None,
    };

    let emu_dll = match dll_source(platform_cache, variant, x64, platform) {
        Ok(p) => p,
        Err(e) => {
            result.error = Some(e);
            return result;
        }
    };

    let interfaces = match generate_interfaces_from_file(target) {
        Ok(s) => s,
        Err(e) => {
            result.error = Some(format!("generate_interfaces failed: {}", e));
            return result;
        }
    };

    let backup = backup_path_for(target);
    if !backup.exists() {
        if let Err(e) = fs::copy(target, &backup) {
            result.error = Some(format!("backup original: {}", e));
            return result;
        }
    }
    result.backup_path = Some(backup.to_string_lossy().to_string());

    if let Err(e) = fs::copy(&emu_dll, target) {
        result.error = Some(format!("copy emulator binary: {}", e));
        return result;
    }

    let parent = match target.parent() {
        Some(p) => p,
        None => {
            result.error = Some("target has no parent dir".into());
            return result;
        }
    };
    let settings_dir = parent.join("steam_settings");
    if let Err(e) = fs::create_dir_all(&settings_dir) {
        result.error = Some(format!("create steam_settings: {}", e));
        return result;
    }

    if let Err(e) = fs::write(settings_dir.join("steam_interfaces.txt"), interfaces) {
        result.error = Some(format!("write steam_interfaces.txt: {}", e));
        return result;
    }
    if let Err(e) = fs::write(settings_dir.join("steam_appid.txt"), app_id.trim()) {
        result.error = Some(format!("write steam_appid.txt: {}", e));
        return result;
    }
    if !installed_app_ids.is_empty() {
        let joined = installed_app_ids
            .iter()
            .map(|s| s.trim())
            .filter(|s| !s.is_empty())
            .collect::<Vec<_>>()
            .join("\n");
        if let Err(e) = fs::write(settings_dir.join("installed_app_ids.txt"), joined) {
            result.error = Some(format!("write installed_app_ids.txt: {}", e));
            return result;
        }
    }

    if let Some(s) = emu_settings {
        if let Err(e) = s.write_to_dir(&settings_dir) {
            result.error = Some(format!("write emu settings: {}", e));
            return result;
        }
    }

    result.success = true;
    result
}

pub fn read_emu_settings_for_target(target: &Path) -> Result<EmuSettings, String> {
    let parent = target
        .parent()
        .ok_or_else(|| "target has no parent dir".to_string())?;
    let settings_dir = parent.join("steam_settings");
    Ok(EmuSettings::read_from_dir(&settings_dir))
}

pub fn write_emu_settings_for_target(target: &Path, settings: &EmuSettings) -> Result<(), String> {
    let parent = target
        .parent()
        .ok_or_else(|| "target has no parent dir".to_string())?;
    if !parent.exists() {
        return Err(format!("game folder not found: {}", parent.display()));
    }
    let settings_dir = parent.join("steam_settings");
    fs::create_dir_all(&settings_dir).map_err(|e| format!("create steam_settings: {}", e))?;
    settings.write_to_dir(&settings_dir)
}

pub fn revert_replacement(target: &Path) -> Result<(), String> {
    if let Some(parent) = target.parent() {
        if !parent.exists() {
            return Err(format!("game folder not found: {}", parent.display()));
        }
    }
    let backup = backup_path_for(target);
    if !backup.exists() {
        return Err(format!("no backup found at {}", backup.display()));
    }
    fs::copy(&backup, target).map_err(|e| format!("restore from backup: {}", e))?;
    let _ = fs::remove_file(&backup);
    if let Some(parent) = target.parent() {
        let settings_dir = parent.join("steam_settings");
        let _ = fs::remove_file(settings_dir.join("steam_interfaces.txt"));
        let _ = fs::remove_file(settings_dir.join("steam_appid.txt"));
        let _ = fs::remove_file(settings_dir.join("installed_app_ids.txt"));
        let _ = fs::remove_dir(&settings_dir);
    }
    Ok(())
}

fn backup_path_for(target: &Path) -> PathBuf {
    let mut p = target.as_os_str().to_owned();
    p.push(".steam.bak");
    PathBuf::from(p)
}
